config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'splash#index'	

  resources :categories, only: %i[index new create] do
    resources :expenses, only: %i[index new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expense, dependent: :destroy
  has_many :expenses, through: :category_expense

  attr_accessor :total

  has_one_attached :icon

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category, class_name: 'Category'
  belongs_to :expense, class_name: 'Expense'
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expense, dependent: :destroy
  has_many :categories, through: :category_expense

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :expenses

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:expenses).where(author: current_user).order(created_at: :desc)

    @categories.each do |category|
      category.total = category.expenses.sum(:amount)
    end

    @total = @categories.sum(&:total)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to categories_path
    else
      flash[:alert] = 'Category was not created.'
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon).merge(author: current_user)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @category = Category.find(params[:category_id])

    @expenses = @category.expenses.includes(:categories).order(created_at: :desc)

    @total = @expenses.sum(:amount)
  end

  def new
    @category = Category.find(params[:category_id])
    @expense = Expense.new
  end

  def create
    category_id = params[:expense][:category_id]
    @category = Category.find(category_id)
    @expense = @category.expenses.new(expense_params)

    if @expense.save
      flash[:notice] = 'Expense was successfully created.'
      redirect_to category_expenses_path(@category)
    else
      flash[:alert] = 'Expense could not be created.'
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount).merge(author: current_user)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true, html: { multipart: true }) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :icon %>
    <%= f.file_field :icon %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class='category'>
  <header class='header'>
    <h1 class='title'>Total Spend</h1>
    <span class='total'><%= number_to_currency(@total) %></span>
  </header>

  <ul class='category_list'>
    <% @categories.each do |category| %>
      <li>
        <%= link_to category_expenses_path(category), class: 'category_item' do %>
          <div class='category_item-grid'>
            <div class='left'>
              <%= image_tag category.icon, width: 50, height: 50 %>
            </div>

            <div class='right'>
              <div class='rigt_grid'>
                <span class='category_name'><%= category.name %></span>
                <span class='category_total'><%= number_to_currency(category.total) %></span>
              </div>

              <span class='category_date'><%= category.created_at.strftime('%b %d, %Y') %></span>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class='actions'>
    <%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/expenses/_form.html.erb
<%= form_with(model: @expense, url: category_expenses_path(@category), local: true) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
      <ul>
        <% @expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.where(author_id: current_user.id), :id, :name, {prompt: "Select a category"} %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Transaction', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<div class='expense'>
  <header class='header'>
    <h1><%= @category.name %></h1>
    <span class='total'><%= number_to_currency(@total) %></span>
  </header>

  <ul class='expense_list'>
    <% @expenses.each do |expense| %>
      <li class='expense_item'>
        <div class='expense_item-grid'>
          <div class='right'>
            <div>
              <span class='expense_name'><%= expense.name %></span>
              <span class='expense_amount'><%= number_to_currency(expense.amount) %></span>
            </div>

            <span class='expense_date'><%= expense.created_at.strftime('%b %d, %Y') %></span>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <div class='actions'>
    <%= link_to 'New Expense', new_category_expense_path(@category), class: 'btn btn-primary' %>
  </div>
</div>

app/views/expenses/new.html.erb
<%= render 'form', expense: @expense %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>Money Trail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track" => "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash_messages' %>
    <main class="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<div class="flash_messages">
  <div class="container">
    <% if flash[:notice] && !flash[:alert] %>
      <p class="notice">
        <%= notice %>
      </p>
    <% end %>
    <% if flash[:alert] && !flash[:notice] %>
      <p class="alert">
        <%= alert %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if signed_in? %>
  <nav class='nav'>
    <div class='container'>
      <ul class='nav_links'>
        <% if controller_name == 'categories' %>
          <li>
            <%= link_to do %>
              <i class="fa-solid fa-home"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path, title: 'Go back' do %>
              <i class="fa-solid fa-angle-left"></i>
            <% end %>
          </li>
        <% end %>
        <li><%= controller_name.upcase %></li>
        <li>
          <%= button_to destroy_user_session_path, method: :delete, title: 'Sign Out' do %>
            <i class="fa-solid fa-sign-out"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/splash/index.html.erb
<div class='splash'>
  <div></div>

  <h1 class='logo'>Money Trail</h1>
  
  <div class='actions'>
    <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-signup' %>
  </div>
</div>